extends Node

signal player_started_recording
signal player_recording_complete
signal player_rewind_complete
signal player_recording_disabled
signal player_recording_enabled
signal set_record_percent(value)
signal add_camera_shake(amount, duration)
